name: cs1090a

channels:
- conda-forge

dependencies:
  - aiohttp
  - arviz
  - beautifulsoup4
  - imageio
  - ipython
  - jupyterlab
  - lxml
  - matplotlib>=3.10
  - numpy
  - openpyxl
  - pandas
  - pillow
  - pip
  - pymc
  - pyarrow
  - python>=3.10
  - requests
  - scikit-learn>=1.7
  - scipy>=1.6
  - seaborn
  - selenium
  - statsmodels
  - tensorflow==2.15.0
  - tqdm
  - pytorch==2.1.0

  - pip:
    - nbopen
    - opencv-python-headless==4.9.0.80
    - otter-grader>=6.1
    - tensorflow_datasets==4.9.4
    - tensorflow_hub==0.16.0
    - tf_keras_vis==0.8.6 # also adds keras